"""Command-line entrypoint for the KSAS XROCKET HMC project."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

from ksas_xrocket import __version__
from ksas_xrocket.audit import EXPECTED_LABELS, DatasetAuditError, audit_dataset
from ksas_xrocket.baselines import BaselineError, run_baselines
from ksas_xrocket.config import (
    ConfigError,
    int_config_value,
    load_yaml_config,
    nested_mapping,
    path_config_value,
)
from ksas_xrocket.prepare import DEFAULT_TARGET_LENGTH, PreparationError, prepare_ksas_tensors
from ksas_xrocket.splits import SplitError, generate_grouped_splits
from ksas_xrocket.task_1_1_explain import (
    Task11ExplanationError,
    run_task_1_1_explanation,
)
from ksas_xrocket.xrocket_adapter import XRocketAdapterError
from ksas_xrocket.xrocket_experiment import XRocketExperimentError, run_xrocket_experiment

DEFAULT_MANIFEST = Path("data/manifests/samples.csv")
DEFAULT_PROCESSED_DIR = Path("data/processed/ksas_m2_raw_padded")
DEFAULT_SPLITS_DIR = Path("data/manifests/splits")
DEFAULT_BASELINE_DIR = Path("results/baselines/m2_raw_padded")
DEFAULT_XROCKET_DIR = Path("results/xrocket/m3_raw_padded")
DEFAULT_TASK_1_1_DIR = Path("results/explanations/task_1_1")

_PLACEHOLDERS = {
    "figures": "M4-M8 report figure generation",
    "report": "M8 technical report build",
    "reproduce": "M8 full reproduction workflow",
}


def build_parser() -> argparse.ArgumentParser:
    """Build the project CLI parser."""
    parser = argparse.ArgumentParser(
        prog="hmc",
        description="KSAS XROCKET human motion computing workflow commands.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )

    subparsers = parser.add_subparsers(dest="command")

    audit_parser = subparsers.add_parser(
        "audit",
        help="Audit raw KSAS CSVs and generate sample manifests.",
    )
    audit_parser.add_argument(
        "--raw-dir",
        type=Path,
        default=Path("data/raw/KSAS-Dataset"),
        help="Raw KSAS dataset directory containing README.md and movements/.",
    )
    audit_parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("data/manifests/samples.csv"),
        help="Output path for the canonical sample manifest.",
    )
    audit_parser.add_argument(
        "--audit-dir",
        type=Path,
        default=Path("results/audit"),
        help="Output directory for audit summary artifacts.",
    )
    audit_parser.add_argument(
        "--provenance",
        type=Path,
        default=Path("data/manifests/ksas_provenance.json"),
        help="Output path for dataset provenance metadata.",
    )
    audit_parser.set_defaults(command="audit")

    prepare_parser = subparsers.add_parser(
        "prepare",
        help="Build M2 padded tensors and participant-grouped split manifests.",
    )
    prepare_parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="YAML config for M2 preprocessing and split defaults.",
    )
    prepare_parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Canonical sample manifest generated by `hmc audit`.",
    )
    prepare_parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory for M2 tensor artifacts.",
    )
    prepare_parser.add_argument(
        "--splits-dir",
        type=Path,
        default=None,
        help="Output directory for grouped split manifests.",
    )
    prepare_parser.add_argument(
        "--target-length",
        type=int,
        default=None,
        help="Padded sequence length for M2 tensors.",
    )
    prepare_parser.add_argument(
        "--n-splits",
        type=int,
        default=None,
        help="Number of stratified participant-grouped folds.",
    )
    prepare_parser.add_argument(
        "--random-state",
        type=int,
        default=None,
        help="Random seed for grouped split generation.",
    )
    prepare_parser.set_defaults(command="prepare")

    baseline_parser = subparsers.add_parser(
        "baseline",
        help="Train M2 statistical baselines on saved grouped folds.",
    )
    baseline_parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="YAML config for M2 baseline defaults.",
    )
    baseline_parser.add_argument(
        "--processed-dir",
        type=Path,
        default=None,
        help="Directory containing M2 tensors.npz.",
    )
    baseline_parser.add_argument(
        "--splits-dir",
        type=Path,
        default=None,
        help="Directory containing M2 grouped split manifests.",
    )
    baseline_parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory for baseline metrics and predictions.",
    )
    baseline_parser.add_argument(
        "--random-state",
        type=int,
        default=None,
        help="Random seed for stochastic baseline estimators.",
    )
    baseline_parser.set_defaults(command="baseline")

    train_parser = subparsers.add_parser(
        "train",
        help="Train the M3 XROCKET models on saved grouped folds.",
    )
    train_parser.add_argument("--config", type=Path, default=None)
    train_parser.add_argument("--processed-dir", type=Path, default=None)
    train_parser.add_argument("--splits-dir", type=Path, default=None)
    train_parser.add_argument("--output-dir", type=Path, default=None)
    train_parser.add_argument("--folds", type=int, nargs="+", default=None)
    train_parser.add_argument("--random-state", type=int, default=None)
    train_parser.add_argument("--batch-size", type=int, default=None)
    train_parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Explicitly replace a non-empty output directory.",
    )
    train_parser.set_defaults(command="train")

    explain_parser = subparsers.add_parser(
        "explain",
        help="Generate M4-M6 explanation analyses.",
    )
    explain_parser.add_argument("--config", type=Path, default=None)
    explain_parser.add_argument("--processed-dir", type=Path, default=None)
    explain_parser.add_argument("--xrocket-dir", type=Path, default=None)
    explain_parser.add_argument("--output-dir", type=Path, default=None)
    explain_parser.add_argument("--random-state", type=int, default=None)
    explain_parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Explicitly replace a non-empty explanation output directory.",
    )
    explain_parser.set_defaults(command="explain")

    for command, milestone in _PLACEHOLDERS.items():
        subparser = subparsers.add_parser(command, help=f"Placeholder for {milestone}.")
        subparser.set_defaults(command=command)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run the CLI."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command is None:
        parser.print_help()
        return 0

    if args.command == "audit":
        try:
            result = audit_dataset(
                raw_dir=args.raw_dir,
                manifest_path=args.manifest,
                audit_dir=args.audit_dir,
                provenance_path=args.provenance,
            )
        except DatasetAuditError as exc:
            print(str(exc))
            return 1

        print("KSAS audit passed.")
        print(f"Manifest: {result.manifest_path}")
        print(f"Summary: {result.summary_path}")
        print(f"Numeric ranges: {result.numeric_ranges_path}")
        print(f"Provenance: {result.provenance_path}")
        return 0

    if args.command == "prepare":
        try:
            config = load_yaml_config(args.config)
            splits_config = nested_mapping(config, "splits")
            manifest = args.manifest or path_config_value(config, "manifest", DEFAULT_MANIFEST)
            output_dir = args.output_dir or path_config_value(
                config,
                "output_dir",
                DEFAULT_PROCESSED_DIR,
            )
            splits_dir = args.splits_dir or path_config_value(
                splits_config,
                "output_dir",
                DEFAULT_SPLITS_DIR,
            )
            target_length = (
                args.target_length
                if args.target_length is not None
                else int_config_value(config, "target_length", DEFAULT_TARGET_LENGTH)
            )
            n_splits = (
                args.n_splits
                if args.n_splits is not None
                else int_config_value(splits_config, "n_splits", 5)
            )
            random_state = (
                args.random_state
                if args.random_state is not None
                else int_config_value(splits_config, "random_state", 42)
            )
            resolved_config = {
                "config": args.config.as_posix() if args.config is not None else None,
                "manifest": manifest.as_posix(),
                "output_dir": output_dir.as_posix(),
                "target": config.get("target", "movement_label_id"),
                "classes": config.get("classes", list(EXPECTED_LABELS)),
                "channels": config.get("channels", "all_raw_imu"),
                "tensor_axis_order": config.get("tensor_axis_order", ["sample", "channel", "time"]),
                "length_strategy": config.get("length_strategy", "right_pad_with_zeros"),
                "target_length": target_length,
                "padding_value": config.get("padding_value", 0.0),
                "normalization": config.get("normalization", "none"),
                "smoothing": config.get("smoothing", "none"),
                "derived_channels": config.get("derived_channels", "none"),
                "splits": {
                    "output_dir": splits_dir.as_posix(),
                    "type": splits_config.get("type", "stratified_group_k_fold"),
                    "group": splits_config.get("group", "split_group"),
                    "n_splits": n_splits,
                    "shuffle": splits_config.get("shuffle", True),
                    "random_state": random_state,
                },
            }
            prep_result = prepare_ksas_tensors(
                manifest_path=manifest,
                output_dir=output_dir,
                target_length=target_length,
                resolved_config=resolved_config,
            )
            split_result = generate_grouped_splits(
                manifest_path=manifest,
                output_dir=splits_dir,
                n_splits=n_splits,
                random_state=random_state,
            )
        except (ConfigError, PreparationError, SplitError) as exc:
            print(str(exc))
            return 1

        print("M2 preparation passed.")
        print(f"Tensors: {prep_result.tensor_path}")
        print(f"Metadata: {prep_result.metadata_path}")
        print(f"Tensor contract: {prep_result.contract_path}")
        print(f"Split manifest: {split_result.split_manifest_path}")
        print(f"Split diagnostics: {split_result.diagnostics_path}")
        return 0

    if args.command == "baseline":
        try:
            config = load_yaml_config(args.config)
            processed_dir = args.processed_dir or path_config_value(
                config,
                "processed_dir",
                DEFAULT_PROCESSED_DIR,
            )
            splits_dir = args.splits_dir or path_config_value(
                config,
                "splits_dir",
                DEFAULT_SPLITS_DIR,
            )
            output_dir = args.output_dir or path_config_value(
                config,
                "output_dir",
                DEFAULT_BASELINE_DIR,
            )
            random_state = (
                args.random_state
                if args.random_state is not None
                else int_config_value(config, "random_state", 42)
            )
            label_ids = label_ids_from_config(config)
            resolved_config = {
                "config": args.config.as_posix() if args.config is not None else None,
                "processed_dir": processed_dir.as_posix(),
                "splits_dir": splits_dir.as_posix(),
                "output_dir": output_dir.as_posix(),
                "target": config.get("target", "movement_label_id"),
                "classes": list(label_ids),
                "feature_source": config.get("feature_source", "raw_padded_tensor"),
                "feature_statistics": config.get("feature_statistics", []),
                "mask_policy": config.get("mask_policy", "ignore_padded_timesteps"),
                "models": config.get(
                    "models",
                    [
                        "majority",
                        "statistical_logistic_regression",
                        "statistical_random_forest",
                    ],
                ),
                "random_state": random_state,
            }
            baseline_result = run_baselines(
                processed_dir=processed_dir,
                splits_dir=splits_dir,
                output_dir=output_dir,
                random_state=random_state,
                label_ids=label_ids,
                resolved_config=resolved_config,
            )
        except (ConfigError, BaselineError) as exc:
            print(str(exc))
            return 1

        print("M2 baselines completed.")
        print(f"Fold metrics: {baseline_result.metrics_path}")
        print(f"Aggregate metrics: {baseline_result.aggregate_metrics_path}")
        print(f"Predictions: {baseline_result.predictions_path}")
        print(f"Confusion matrices: {baseline_result.confusion_matrices_path}")
        print(f"Provenance: {baseline_result.provenance_path}")
        return 0

    if args.command == "train":
        try:
            config = load_yaml_config(args.config)
            xrocket_config = nested_mapping(config, "xrocket")
            classifiers_config = nested_mapping(config, "classifiers")
            rf_config = nested_mapping(classifiers_config, "random_forest")
            logistic_config = nested_mapping(classifiers_config, "logistic_regression")
            processed_dir = args.processed_dir or path_config_value(
                config,
                "processed_dir",
                DEFAULT_PROCESSED_DIR,
            )
            splits_dir = args.splits_dir or path_config_value(
                config,
                "splits_dir",
                DEFAULT_SPLITS_DIR,
            )
            output_dir = args.output_dir or path_config_value(
                config,
                "output_dir",
                DEFAULT_XROCKET_DIR,
            )
            random_state = (
                args.random_state
                if args.random_state is not None
                else int_config_value(config, "random_state", 42)
            )
            batch_size = (
                args.batch_size
                if args.batch_size is not None
                else int_config_value(config, "batch_size", 16)
            )
            folds = folds_from_config(config, args.folds)
            label_ids = label_ids_from_config(config)
            resolved_config = {
                "config": args.config.as_posix() if args.config is not None else None,
                "processed_dir": processed_dir.as_posix(),
                "splits_dir": splits_dir.as_posix(),
                "output_dir": output_dir.as_posix(),
                "target": config.get("target", "movement_label_id"),
                "classes": list(label_ids),
                "folds": list(folds) if folds is not None else "all",
                "random_state": random_state,
                "batch_size": batch_size,
                "xrocket": {
                    "feature_cap": int_config_value(xrocket_config, "feature_cap", 10_000),
                    "kernel_length": int_config_value(xrocket_config, "kernel_length", 9),
                    "max_dilations": int_config_value(xrocket_config, "max_dilations", 32),
                    "combination_order": int_config_value(xrocket_config, "combination_order", 1),
                    "combination_method": xrocket_config.get("combination_method", "additive"),
                    "nominal_sampling_rate_hz": float(
                        xrocket_config.get("nominal_sampling_rate_hz", 50.0)
                    ),
                },
                "classifiers": {
                    "random_forest": {
                        "n_estimators": int_config_value(rf_config, "n_estimators", 500),
                        "class_weight": "balanced",
                        "max_features": "sqrt",
                        "n_jobs": -1,
                    },
                    "logistic_regression": {
                        "max_iter": int_config_value(logistic_config, "max_iter", 2000),
                        "penalty": "l2",
                        "standardize": True,
                    },
                },
                "padding_diagnostics": True,
            }
            xrocket_result = run_xrocket_experiment(
                processed_dir=processed_dir,
                splits_dir=splits_dir,
                output_dir=output_dir,
                folds=folds,
                random_state=random_state,
                label_ids=label_ids,
                batch_size=batch_size,
                feature_cap=int(resolved_config["xrocket"]["feature_cap"]),
                kernel_length=int(resolved_config["xrocket"]["kernel_length"]),
                max_dilations=int(resolved_config["xrocket"]["max_dilations"]),
                combination_order=int(resolved_config["xrocket"]["combination_order"]),
                combination_method=str(resolved_config["xrocket"]["combination_method"]),
                nominal_sampling_rate_hz=float(
                    resolved_config["xrocket"]["nominal_sampling_rate_hz"]
                ),
                random_forest_estimators=int(
                    resolved_config["classifiers"]["random_forest"]["n_estimators"]
                ),
                logistic_max_iter=int(
                    resolved_config["classifiers"]["logistic_regression"]["max_iter"]
                ),
                overwrite=args.overwrite,
                resolved_config=resolved_config,
            )
        except (
            ConfigError,
            BaselineError,
            XRocketAdapterError,
            XRocketExperimentError,
            TypeError,
            ValueError,
        ) as exc:
            print(str(exc))
            return 1

        print("M3 XROCKET experiment completed.")
        print(f"Fold metrics: {xrocket_result.metrics_path}")
        print(f"Aggregate metrics: {xrocket_result.aggregate_metrics_path}")
        print(f"Predictions: {xrocket_result.predictions_path}")
        print(f"Confusion matrices: {xrocket_result.confusion_matrices_path}")
        print(f"Runtime: {xrocket_result.runtime_path}")
        print(f"Provenance: {xrocket_result.provenance_path}")
        return 0

    if args.command == "explain":
        try:
            config = load_yaml_config(args.config)
            task_name = str(config.get("task", "task_1_1"))
            if task_name != "task_1_1":
                raise ConfigError(f"Unsupported explanation task: {task_name}")
            validation_config = nested_mapping(config, "validation")
            models_config = nested_mapping(config, "models")
            rf_config = nested_mapping(models_config, "random_forest")
            processed_dir = args.processed_dir or path_config_value(
                config,
                "processed_dir",
                DEFAULT_PROCESSED_DIR,
            )
            xrocket_dir = args.xrocket_dir or path_config_value(
                config,
                "xrocket_dir",
                DEFAULT_XROCKET_DIR,
            )
            output_dir = args.output_dir or path_config_value(
                config,
                "output_dir",
                DEFAULT_TASK_1_1_DIR,
            )
            random_state = (
                args.random_state
                if args.random_state is not None
                else int_config_value(config, "random_state", 42)
            )
            label_ids = label_ids_from_config(config)
            random_forest_estimators = int_config_value(rf_config, "n_estimators", 500)
            permutation_repeats = int_config_value(
                validation_config,
                "permutation_repeats",
                5,
            )
            top_k = int_config_value(validation_config, "top_k", 3)
            resolved_config = {
                "config": args.config.as_posix() if args.config is not None else None,
                "task": task_name,
                "processed_dir": processed_dir.as_posix(),
                "xrocket_dir": xrocket_dir.as_posix(),
                "output_dir": output_dir.as_posix(),
                "classes": list(label_ids),
                "random_state": random_state,
                "validation": {
                    "group_levels": validation_config.get(
                        "group_levels",
                        ["sensor_family", "channel"],
                    ),
                    "permutation_repeats": permutation_repeats,
                    "top_k": top_k,
                },
                "models": {
                    "random_forest": {
                        "n_estimators": random_forest_estimators,
                        "class_weight": "balanced",
                        "max_features": "sqrt",
                        "n_jobs": -1,
                    }
                },
            }
            explanation_result = run_task_1_1_explanation(
                processed_dir=processed_dir,
                xrocket_dir=xrocket_dir,
                output_dir=output_dir,
                label_ids=label_ids,
                random_state=random_state,
                random_forest_estimators=random_forest_estimators,
                permutation_repeats=permutation_repeats,
                top_k=top_k,
                overwrite=args.overwrite,
                resolved_config=resolved_config,
            )
        except (ConfigError, BaselineError, Task11ExplanationError, TypeError, ValueError) as exc:
            print(str(exc))
            return 1

        print("Task 1.1 explanation analysis completed.")
        print(f"Native importance: {explanation_result.native_importance_path}")
        print(f"Ablation metrics: {explanation_result.ablation_path}")
        print(f"Permutation importance: {explanation_result.permutation_path}")
        print(f"Method agreement: {explanation_result.method_agreement_path}")
        print(f"Answer draft: {explanation_result.answer_path}")
        print(f"Provenance: {explanation_result.provenance_path}")
        return 0

    milestone = _PLACEHOLDERS[args.command]
    print(f"`hmc {args.command}` is reserved for {milestone}; no data or model work runs in M0.")
    return 0


def label_ids_from_config(config: dict[str, object]) -> tuple[int, ...]:
    """Return configured class labels or the M2 six-class default."""
    values = config.get("classes", list(EXPECTED_LABELS))
    if not isinstance(values, list) or not values:
        raise ConfigError("Config field 'classes' must be a non-empty list")
    try:
        return tuple(int(value) for value in values)
    except (TypeError, ValueError) as exc:
        raise ConfigError("Config field 'classes' must contain integer labels") from exc


def folds_from_config(
    config: dict[str, object],
    cli_folds: list[int] | None,
) -> tuple[int, ...] | None:
    """Return selected fold IDs, with CLI values taking precedence."""
    values: object = cli_folds if cli_folds is not None else config.get("folds")
    if values is None or values == "all":
        return None
    if not isinstance(values, list) or not values:
        raise ConfigError("Config field 'folds' must be 'all' or a non-empty list")
    try:
        folds = tuple(int(value) for value in values)
    except (TypeError, ValueError) as exc:
        raise ConfigError("Config field 'folds' must contain integers") from exc
    if len(set(folds)) != len(folds) or any(fold < 0 for fold in folds):
        raise ConfigError("Config field 'folds' must contain unique non-negative integers")
    return folds


if __name__ == "__main__":
    raise SystemExit(main())
