"""Command-line entrypoint for the KSAS XROCKET HMC project."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

from ksas_xrocket import __version__
from ksas_xrocket.audit import EXPECTED_LABELS, DatasetAuditError, audit_dataset
from ksas_xrocket.baselines import BaselineError, run_baselines
from ksas_xrocket.config import (
    ConfigError,
    int_config_value,
    load_yaml_config,
    nested_mapping,
    path_config_value,
)
from ksas_xrocket.prepare import DEFAULT_TARGET_LENGTH, PreparationError, prepare_ksas_tensors
from ksas_xrocket.splits import SplitError, generate_grouped_splits

DEFAULT_MANIFEST = Path("data/manifests/samples.csv")
DEFAULT_PROCESSED_DIR = Path("data/processed/ksas_m2_raw_padded")
DEFAULT_SPLITS_DIR = Path("data/manifests/splits")
DEFAULT_BASELINE_DIR = Path("results/baselines/m2_raw_padded")

_PLACEHOLDERS = {
    "train": "M3 XROCKET model training",
    "explain": "M4-M6 explanation analyses",
    "figures": "M4-M8 report figure generation",
    "report": "M8 technical report build",
    "reproduce": "M8 full reproduction workflow",
}


def build_parser() -> argparse.ArgumentParser:
    """Build the project CLI parser."""
    parser = argparse.ArgumentParser(
        prog="hmc",
        description="KSAS XROCKET human motion computing workflow commands.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )

    subparsers = parser.add_subparsers(dest="command")

    audit_parser = subparsers.add_parser(
        "audit",
        help="Audit raw KSAS CSVs and generate sample manifests.",
    )
    audit_parser.add_argument(
        "--raw-dir",
        type=Path,
        default=Path("data/raw/KSAS-Dataset"),
        help="Raw KSAS dataset directory containing README.md and movements/.",
    )
    audit_parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("data/manifests/samples.csv"),
        help="Output path for the canonical sample manifest.",
    )
    audit_parser.add_argument(
        "--audit-dir",
        type=Path,
        default=Path("results/audit"),
        help="Output directory for audit summary artifacts.",
    )
    audit_parser.add_argument(
        "--provenance",
        type=Path,
        default=Path("data/manifests/ksas_provenance.json"),
        help="Output path for dataset provenance metadata.",
    )
    audit_parser.set_defaults(command="audit")

    prepare_parser = subparsers.add_parser(
        "prepare",
        help="Build M2 padded tensors and participant-grouped split manifests.",
    )
    prepare_parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="YAML config for M2 preprocessing and split defaults.",
    )
    prepare_parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Canonical sample manifest generated by `hmc audit`.",
    )
    prepare_parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory for M2 tensor artifacts.",
    )
    prepare_parser.add_argument(
        "--splits-dir",
        type=Path,
        default=None,
        help="Output directory for grouped split manifests.",
    )
    prepare_parser.add_argument(
        "--target-length",
        type=int,
        default=None,
        help="Padded sequence length for M2 tensors.",
    )
    prepare_parser.add_argument(
        "--n-splits",
        type=int,
        default=None,
        help="Number of stratified participant-grouped folds.",
    )
    prepare_parser.add_argument(
        "--random-state",
        type=int,
        default=None,
        help="Random seed for grouped split generation.",
    )
    prepare_parser.set_defaults(command="prepare")

    baseline_parser = subparsers.add_parser(
        "baseline",
        help="Train M2 statistical baselines on saved grouped folds.",
    )
    baseline_parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="YAML config for M2 baseline defaults.",
    )
    baseline_parser.add_argument(
        "--processed-dir",
        type=Path,
        default=None,
        help="Directory containing M2 tensors.npz.",
    )
    baseline_parser.add_argument(
        "--splits-dir",
        type=Path,
        default=None,
        help="Directory containing M2 grouped split manifests.",
    )
    baseline_parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory for baseline metrics and predictions.",
    )
    baseline_parser.add_argument(
        "--random-state",
        type=int,
        default=None,
        help="Random seed for stochastic baseline estimators.",
    )
    baseline_parser.set_defaults(command="baseline")

    for command, milestone in _PLACEHOLDERS.items():
        subparser = subparsers.add_parser(command, help=f"Placeholder for {milestone}.")
        subparser.set_defaults(command=command)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run the CLI."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command is None:
        parser.print_help()
        return 0

    if args.command == "audit":
        try:
            result = audit_dataset(
                raw_dir=args.raw_dir,
                manifest_path=args.manifest,
                audit_dir=args.audit_dir,
                provenance_path=args.provenance,
            )
        except DatasetAuditError as exc:
            print(str(exc))
            return 1

        print("KSAS audit passed.")
        print(f"Manifest: {result.manifest_path}")
        print(f"Summary: {result.summary_path}")
        print(f"Numeric ranges: {result.numeric_ranges_path}")
        print(f"Provenance: {result.provenance_path}")
        return 0

    if args.command == "prepare":
        try:
            config = load_yaml_config(args.config)
            splits_config = nested_mapping(config, "splits")
            manifest = args.manifest or path_config_value(config, "manifest", DEFAULT_MANIFEST)
            output_dir = args.output_dir or path_config_value(
                config,
                "output_dir",
                DEFAULT_PROCESSED_DIR,
            )
            splits_dir = args.splits_dir or path_config_value(
                splits_config,
                "output_dir",
                DEFAULT_SPLITS_DIR,
            )
            target_length = (
                args.target_length
                if args.target_length is not None
                else int_config_value(config, "target_length", DEFAULT_TARGET_LENGTH)
            )
            n_splits = (
                args.n_splits
                if args.n_splits is not None
                else int_config_value(splits_config, "n_splits", 5)
            )
            random_state = (
                args.random_state
                if args.random_state is not None
                else int_config_value(splits_config, "random_state", 42)
            )
            resolved_config = {
                "config": args.config.as_posix() if args.config is not None else None,
                "manifest": manifest.as_posix(),
                "output_dir": output_dir.as_posix(),
                "target": config.get("target", "movement_label_id"),
                "classes": config.get("classes", list(EXPECTED_LABELS)),
                "channels": config.get("channels", "all_raw_imu"),
                "tensor_axis_order": config.get("tensor_axis_order", ["sample", "channel", "time"]),
                "length_strategy": config.get("length_strategy", "right_pad_with_zeros"),
                "target_length": target_length,
                "padding_value": config.get("padding_value", 0.0),
                "normalization": config.get("normalization", "none"),
                "smoothing": config.get("smoothing", "none"),
                "derived_channels": config.get("derived_channels", "none"),
                "splits": {
                    "output_dir": splits_dir.as_posix(),
                    "type": splits_config.get("type", "stratified_group_k_fold"),
                    "group": splits_config.get("group", "split_group"),
                    "n_splits": n_splits,
                    "shuffle": splits_config.get("shuffle", True),
                    "random_state": random_state,
                },
            }
            prep_result = prepare_ksas_tensors(
                manifest_path=manifest,
                output_dir=output_dir,
                target_length=target_length,
                resolved_config=resolved_config,
            )
            split_result = generate_grouped_splits(
                manifest_path=manifest,
                output_dir=splits_dir,
                n_splits=n_splits,
                random_state=random_state,
            )
        except (ConfigError, PreparationError, SplitError) as exc:
            print(str(exc))
            return 1

        print("M2 preparation passed.")
        print(f"Tensors: {prep_result.tensor_path}")
        print(f"Metadata: {prep_result.metadata_path}")
        print(f"Tensor contract: {prep_result.contract_path}")
        print(f"Split manifest: {split_result.split_manifest_path}")
        print(f"Split diagnostics: {split_result.diagnostics_path}")
        return 0

    if args.command == "baseline":
        try:
            config = load_yaml_config(args.config)
            processed_dir = args.processed_dir or path_config_value(
                config,
                "processed_dir",
                DEFAULT_PROCESSED_DIR,
            )
            splits_dir = args.splits_dir or path_config_value(
                config,
                "splits_dir",
                DEFAULT_SPLITS_DIR,
            )
            output_dir = args.output_dir or path_config_value(
                config,
                "output_dir",
                DEFAULT_BASELINE_DIR,
            )
            random_state = (
                args.random_state
                if args.random_state is not None
                else int_config_value(config, "random_state", 42)
            )
            label_ids = label_ids_from_config(config)
            resolved_config = {
                "config": args.config.as_posix() if args.config is not None else None,
                "processed_dir": processed_dir.as_posix(),
                "splits_dir": splits_dir.as_posix(),
                "output_dir": output_dir.as_posix(),
                "target": config.get("target", "movement_label_id"),
                "classes": list(label_ids),
                "feature_source": config.get("feature_source", "raw_padded_tensor"),
                "feature_statistics": config.get("feature_statistics", []),
                "mask_policy": config.get("mask_policy", "ignore_padded_timesteps"),
                "models": config.get(
                    "models",
                    [
                        "majority",
                        "statistical_logistic_regression",
                        "statistical_random_forest",
                    ],
                ),
                "random_state": random_state,
            }
            baseline_result = run_baselines(
                processed_dir=processed_dir,
                splits_dir=splits_dir,
                output_dir=output_dir,
                random_state=random_state,
                label_ids=label_ids,
                resolved_config=resolved_config,
            )
        except (ConfigError, BaselineError) as exc:
            print(str(exc))
            return 1

        print("M2 baselines completed.")
        print(f"Fold metrics: {baseline_result.metrics_path}")
        print(f"Aggregate metrics: {baseline_result.aggregate_metrics_path}")
        print(f"Predictions: {baseline_result.predictions_path}")
        print(f"Confusion matrices: {baseline_result.confusion_matrices_path}")
        print(f"Provenance: {baseline_result.provenance_path}")
        return 0

    milestone = _PLACEHOLDERS[args.command]
    print(f"`hmc {args.command}` is reserved for {milestone}; no data or model work runs in M0.")
    return 0


def label_ids_from_config(config: dict[str, object]) -> tuple[int, ...]:
    """Return configured class labels or the M2 six-class default."""
    values = config.get("classes", list(EXPECTED_LABELS))
    if not isinstance(values, list) or not values:
        raise ConfigError("Config field 'classes' must be a non-empty list")
    try:
        return tuple(int(value) for value in values)
    except (TypeError, ValueError) as exc:
        raise ConfigError("Config field 'classes' must contain integer labels") from exc


if __name__ == "__main__":
    raise SystemExit(main())
